spring:
  datasource:   #数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fight?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    dbcp2:
      max-idle: 10
      max-wait-millis: 1000
      min-idle: 5
      initial-size: 5

mybatis:  #扫描XML文件，与实际文件路径对应
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8080  #端口设置
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 10